// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// Hertz server will be listening on IP address 0.0.0.0
	// and the port number is 1111
	h := server.Default(server.WithHostPorts("0.0.0.0:1111"))

	register(h)
	h.Spin()
}
