// Code generated by Kitex v0.6.1. DO NOT EDIT.

package calculatorservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	orbital "test4/hertz/kitex_gen/orbital"
)

func serviceInfo() *kitex.ServiceInfo {
	return calculatorServiceServiceInfo
}

var calculatorServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CalculatorService"
	handlerType := (*orbital.CalculatorService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Add": kitex.NewMethodInfo(addHandler, newCalculatorServiceAddArgs, newCalculatorServiceAddResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "orbital",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func addHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*orbital.CalculatorServiceAddArgs)
	realResult := result.(*orbital.CalculatorServiceAddResult)
	success, err := handler.(orbital.CalculatorService).Add(ctx, realArg.Inputs)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCalculatorServiceAddArgs() interface{} {
	return orbital.NewCalculatorServiceAddArgs()
}

func newCalculatorServiceAddResult() interface{} {
	return orbital.NewCalculatorServiceAddResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Add(ctx context.Context, inputs *orbital.Variable) (r *orbital.Result_, err error) {
	var _args orbital.CalculatorServiceAddArgs
	_args.Inputs = inputs
	var _result orbital.CalculatorServiceAddResult
	if err = p.c.Call(ctx, "Add", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
