// Code generated by hertz generator.

package api

import (
	"context"

	api "github.com/cloudwego/hertz/hertz_server/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryUser .
// @router User/query [GET]
func QueryUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.QueryUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.QueryUserResponse)

	c.JSON(consts.StatusOK, resp)
}

// AddUser .
// @router User/Add [POST]
func AddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.AddUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.AddUserResponse)

	c.JSON(consts.StatusOK, resp)
}
