// Code generated by Kitex v0.6.1. DO NOT EDIT.
package echoservice

import (
	server0 "github.com/cloudwego/kitex/gcf/idl/kitex_gen/kitex/test/server"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler server0.EchoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
