// Code generated by Kitex v0.6.1. DO NOT EDIT.

package echoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	server0 "github.com/cloudwego/kitex/gcf/idl/kitex_gen/kitex/test/server"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return echoServiceServiceInfo
}

var echoServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "EchoService"
	handlerType := (*server0.EchoService)(nil)
	methods := map[string]kitex.MethodInfo{
		"EchoMethod": kitex.NewMethodInfo(echoMethodHandler, newEchoServiceEchoMethodArgs, newEchoServiceEchoMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "server",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*server0.EchoServiceEchoMethodArgs)
	realResult := result.(*server0.EchoServiceEchoMethodResult)
	success, err := handler.(server0.EchoService).EchoMethod(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEchoServiceEchoMethodArgs() interface{} {
	return server0.NewEchoServiceEchoMethodArgs()
}

func newEchoServiceEchoMethodResult() interface{} {
	return server0.NewEchoServiceEchoMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoMethod(ctx context.Context, req *server0.EchoReq) (r *server0.EchoResp, err error) {
	var _args server0.EchoServiceEchoMethodArgs
	_args.Req = req
	var _result server0.EchoServiceEchoMethodResult
	if err = p.c.Call(ctx, "EchoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
