// Code generated by Kitex v0.6.1. DO NOT EDIT.
package calculatorservice

import (
	server "github.com/cloudwego/kitex/server"
	orbital "test4/kitex/kitex_gen/orbital"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler orbital.CalculatorService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
